CREATE TABLE IF NOT EXISTS category(category_id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL UNIQUE, category_name TEXT, category_parent INTEGER, FOREIGN KEY(category_parent) REFERENCES category(id));
CREATE TABLE IF NOT EXISTS item(item_id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL UNIQUE, item_name TEXT, item_description TEXT, item_parent INTEGER,category_id INTEGER, number_times_used INTEGER, price TEXT, pic_location TEXT , FOREIGN KEY(item_parent) REFERENCES item(id), FOREIGN KEY(category_id) REFERENCES category(category_id));
CREATE TABLE IF NOT EXISTS lists(lists_id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL UNIQUE, lists_name TEXT);
CREATE TABLE IF NOT EXISTS item_list(item_list_id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL UNIQUE, list_id INTEGER, item_id INTEGER, FOREIGN KEY(item_id) REFERENCES item(id),FOREIGN KEY(list_id) REFERENCES lists(id));
INSERT INTO category(category_id,category_name,category_parent) VALUES (1,'Appliances',NULL);
INSERT INTO category(category_id,category_name,category_parent) VALUES (2,'Clothing',NULL);
INSERT INTO category(category_id,category_name,category_parent) VALUES (3,'Decorations',NULL);
INSERT INTO category(category_id,category_name,category_parent) VALUES (4,'Consumables',NULL);
INSERT INTO category(category_id,category_name,category_parent) VALUES (5,'Crafts',NULL);
INSERT INTO category(category_id,category_name,category_parent) VALUES (6,'Collections',NULL);
INSERT INTO category(category_id,category_name,category_parent) VALUES (7,'Documents',NULL);
INSERT INTO category(category_id,category_name,category_parent) VALUES (8,'Furnishings',NULL);
INSERT INTO category(category_id,category_name,category_parent) VALUES (9,'Furniture',NULL);
INSERT INTO category(category_id,category_name,category_parent) VALUES (10,'Health',NULL);
INSERT INTO category(category_id,category_name,category_parent) VALUES (11,'Sporting Goods',NULL);
INSERT INTO category(category_id,category_name,category_parent) VALUES (12,'Electronics',NULL);
INSERT INTO category(category_id,category_name,category_parent) VALUES (13,'Toys',NULL);
INSERT INTO category(category_id,category_name,category_parent) VALUES (14,'Tools',NULL);
INSERT INTO category(category_id,category_name,category_parent) VALUES (15,'Spare parts',NULL);
INSERT INTO category(category_id,category_name,category_parent) VALUES (16,'Cleaning',1);
INSERT INTO category(category_id,category_name,category_parent) VALUES (17,'Food Prep',1);
INSERT INTO category(category_id,category_name,category_parent) VALUES (18,'Cookware',1);
INSERT INTO category(category_id,category_name,category_parent) VALUES (19,'Fans',1);
INSERT INTO category(category_id,category_name,category_parent) VALUES (20,'Bathroom',1);
INSERT INTO category(category_id,category_name,category_parent) VALUES (21,'Accessories',2);
INSERT INTO category(category_id,category_name,category_parent) VALUES (22,'Footwear',2);
INSERT INTO category(category_id,category_name,category_parent) VALUES (23,'Formal',2);
INSERT INTO category(category_id,category_name,category_parent) VALUES (24,'Headware',2);
INSERT INTO category(category_id,category_name,category_parent) VALUES (25,'Sports',2);
INSERT INTO category(category_id,category_name,category_parent) VALUES (26,'Street clothes',2);
INSERT INTO category(category_id,category_name,category_parent) VALUES (27,'Underwear',2);
INSERT INTO category(category_id,category_name,category_parent) VALUES (28,'Outerwear',2);
INSERT INTO category(category_id,category_name,category_parent) VALUES (29,'Functional Accessories',21);
INSERT INTO category(category_id,category_name,category_parent) VALUES (30,'Fashion Accessories',21);
INSERT INTO category(category_id,category_name,category_parent) VALUES (31,'Jewelry',21);
INSERT INTO category(category_id,category_name,category_parent) VALUES (32,'Shoes',22);
INSERT INTO category(category_id,category_name,category_parent) VALUES (33,'Boots',22);
INSERT INTO category(category_id,category_name,category_parent) VALUES (34,'Sandals',22);
INSERT INTO category(category_id,category_name,category_parent) VALUES (35,'Work Clothes',23);
INSERT INTO category(category_id,category_name,category_parent) VALUES (36,'Fancy Clothes',23);
INSERT INTO category(category_id,category_name,category_parent) VALUES (37,'Hats',24);
INSERT INTO category(category_id,category_name,category_parent) VALUES (38,'Scarves',24);
INSERT INTO category(category_id,category_name,category_parent) VALUES (39,'Swimwear',25);
INSERT INTO category(category_id,category_name,category_parent) VALUES (40,'Workout Clothes',25);
INSERT INTO category(category_id,category_name,category_parent) VALUES (41,'Tops',26);
INSERT INTO category(category_id,category_name,category_parent) VALUES (42,'Bottoms',26);
INSERT INTO category(category_id,category_name,category_parent) VALUES (43,'Dresses',26);
INSERT INTO category(category_id,category_name,category_parent) VALUES (44,'Light Jackets',28);
INSERT INTO category(category_id,category_name,category_parent) VALUES (45,'Heavy Jackets',28);
INSERT INTO category(category_id,category_name,category_parent) VALUES (46,'Artwork',3);
INSERT INTO category(category_id,category_name,category_parent) VALUES (47,'Accent pieces',3);
INSERT INTO category(category_id,category_name,category_parent) VALUES (48,'Souvenirs',3);
INSERT INTO category(category_id,category_name,category_parent) VALUES (49,'Food',4);
INSERT INTO category(category_id,category_name,category_parent) VALUES (50,'Drinks',4);
INSERT INTO category(category_id,category_name,category_parent) VALUES (51,'Ingredients',4);
INSERT INTO category(category_id,category_name,category_parent) VALUES (52,'Canned/Bottled',50);
INSERT INTO category(category_id,category_name,category_parent) VALUES (53,'Frozen',50);
INSERT INTO category(category_id,category_name,category_parent) VALUES (54,'Long-life',50);
INSERT INTO category(category_id,category_name,category_parent) VALUES (55,'Snacks',50);
INSERT INTO category(category_id,category_name,category_parent) VALUES (56,'Beer',51);
INSERT INTO category(category_id,category_name,category_parent) VALUES (57,'Alcohol',51);
INSERT INTO category(category_id,category_name,category_parent) VALUES (58,'Wine',51);
INSERT INTO category(category_id,category_name,category_parent) VALUES (59,'Soft Drinks',51);
INSERT INTO category(category_id,category_name,category_parent) VALUES (60,'Spices',52);
INSERT INTO category(category_id,category_name,category_parent) VALUES (61,'Grains',52);
INSERT INTO category(category_id,category_name,category_parent) VALUES (62,'Legumes',52);
INSERT INTO category(category_id,category_name,category_parent) VALUES (63,'Pastas',52);
INSERT INTO category(category_id,category_name,category_parent) VALUES (64,'Sauces',52);
INSERT INTO category(category_id,category_name,category_parent) VALUES (65,'Seasoning',52);
INSERT INTO category(category_id,category_name,category_parent) VALUES (66,'Building Materials',5);
INSERT INTO category(category_id,category_name,category_parent) VALUES (67,'Fabrics',5);
INSERT INTO category(category_id,category_name,category_parent) VALUES (68,'Wood',67);
INSERT INTO category(category_id,category_name,category_parent) VALUES (69,'Plastic',67);
INSERT INTO category(category_id,category_name,category_parent) VALUES (70,'Fasteners',67);
INSERT INTO category(category_id,category_name,category_parent) VALUES (71,'Pipe',67);
INSERT INTO category(category_id,category_name,category_parent) VALUES (72,'Cards',6);
INSERT INTO category(category_id,category_name,category_parent) VALUES (73,'Publications',6);
INSERT INTO category(category_id,category_name,category_parent) VALUES (74,'Books',73);
INSERT INTO category(category_id,category_name,category_parent) VALUES (75,'Textbooks',73);
INSERT INTO category(category_id,category_name,category_parent) VALUES (76,'Magazines',73);
INSERT INTO category(category_id,category_name,category_parent) VALUES (77,'Newspapaers',73);
INSERT INTO category(category_id,category_name,category_parent) VALUES (78,'Offical Documents',7);
INSERT INTO category(category_id,category_name,category_parent) VALUES (79,'Notes',7);
INSERT INTO category(category_id,category_name,category_parent) VALUES (80,'Statements',7);
INSERT INTO category(category_id,category_name,category_parent) VALUES (81,'Stationary',7);
INSERT INTO category(category_id,category_name,category_parent) VALUES (82,'Towels',8);
INSERT INTO category(category_id,category_name,category_parent) VALUES (83,'Bedding',8);
INSERT INTO category(category_id,category_name,category_parent) VALUES (84,'Pillows',8);
INSERT INTO category(category_id,category_name,category_parent) VALUES (85,'Fixtures',9);
INSERT INTO category(category_id,category_name,category_parent) VALUES (86,'Cabinetry',9);
INSERT INTO category(category_id,category_name,category_parent) VALUES (87,'Tables',9);
INSERT INTO category(category_id,category_name,category_parent) VALUES (88,'Lighting',9);
INSERT INTO category(category_id,category_name,category_parent) VALUES (89,'Outdoor',9);
INSERT INTO category(category_id,category_name,category_parent) VALUES (90,'Cosmetics',10);
INSERT INTO category(category_id,category_name,category_parent) VALUES (91,'Hygiene',10);
INSERT INTO category(category_id,category_name,category_parent) VALUES (92,'Medical Products',10);
INSERT INTO category(category_id,category_name,category_parent) VALUES (93,'Balls',11);
INSERT INTO category(category_id,category_name,category_parent) VALUES (94,'Gym Equipment',11);
INSERT INTO category(category_id,category_name,category_parent) VALUES (95,'Raquets',11);
INSERT INTO category(category_id,category_name,category_parent) VALUES (96,'Computers',12);
INSERT INTO category(category_id,category_name,category_parent) VALUES (97,'Headphones',12);
INSERT INTO category(category_id,category_name,category_parent) VALUES (98,'Wires',12);
INSERT INTO category(category_id,category_name,category_parent) VALUES (99,'Flash Drives',12);
INSERT INTO category(category_id,category_name,category_parent) VALUES (100,'Misc',12);
INSERT INTO category(category_id,category_name,category_parent) VALUES (101,'Board games',13);
INSERT INTO category(category_id,category_name,category_parent) VALUES (102,'Video Games',13);
INSERT INTO category(category_id,category_name,category_parent) VALUES (103,'Consoles',13);
INSERT INTO category(category_id,category_name,category_parent) VALUES (104,'Card Games',13);
INSERT INTO category(category_id,category_name,category_parent) VALUES (105,'Gardening Tools',14);
INSERT INTO category(category_id,category_name,category_parent) VALUES (106,'Automotive Tools',14);
INSERT INTO category(category_id,category_name,category_parent) VALUES (107,'Household Tools',14);
